# Welcome to Jekyll!
#

# Site settings
title: Ayako + Terrell
description: |
  Yokohama, Japan

  June 16, 2019

  Check-in: 3:30pm |
  Ceremony: 4:00pm |
  Reception: 5:00pm
owner: Ayako + Terrell Broomer # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: domofactor@github.com
baseurl: "/wedding" # the subpath of your site, e.g. /blog
url: "https://tanda.github.io" # the base hostname & protocol for your site
social:
  github: https://github.com/tanda

# Build settings
markdown: kramdown
#sass:
#  style: compressed
